# Generated by Django 3.2.20 on 2023-08-20 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('intervention', models.CharField(choices=[('maintenance', 'Maintenance'), ('installation', 'Installation'), ('incident', 'Incident')], max_length=20)),
                ('status', models.CharField(default='En attente', max_length=20)),
                ('priorite', models.CharField(max_length=20)),
                ('description', models.CharField(default='description', max_length=500)),
                ('ok', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='media/profile/ims.jpg', upload_to='media/profile', verbose_name='profile')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='prenom')),
                ('tel', models.CharField(max_length=20, verbose_name='telephone')),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='matricune')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('vitesse_execution', models.FloatField(default=0.0, verbose_name="Vitesse d'exécution")),
                ('efficacite', models.FloatField(default=0.0, verbose_name='Efficacité')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Technicien',
                'verbose_name_plural': 'Techniciens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TechnicienTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tache')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.technicien')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_os', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'OS")),
                ('rapport_text', models.TextField(verbose_name='Rapport')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tache')),
                ('techniciens', models.ManyToManyField(to='project.Technicien', verbose_name='Techniciens ayant effectué la tâche')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('creation', 'Création'), ('attribution', 'Attribution'), ('effectuation', 'Effectuation')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tache')),
            ],
        ),
    ]
